DROP TABLE IF EXISTS inventories;

CREATE TABLE inventories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT not NULL,
  description TEXT NOT NULL,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
