DROP TABLE IF EXISTS inventories;

CREATE TABLE inventories (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT not NULL,
  description TEXT NOT NULL,
  price REAL NOT NULL,
  image TEXT NOT NULL,
  stock INTEGER DEFAULT 0,
  created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
